// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function AddStepToTask(arg1:string,arg2:string):Promise<void>;

export function CreateTask(arg1:string):Promise<void>;

export function DeleteAllTasks():Promise<void>;

export function DeleteStep(arg1:string,arg2:string):Promise<void>;

export function DeleteTask(arg1:string):Promise<void>;

export function EditStep(arg1:string,arg2:string,arg3:string):Promise<void>;

export function EditTask(arg1:string,arg2:string):Promise<void>;

export function GetStepsByTaskId(arg1:string,arg2:number):Promise<models.StepTreeResponse>;

export function GetTasks(arg1:number):Promise<models.TaskTreeResponse>;

export function SetContext(arg1:context.Context):Promise<void>;

export function ToggleStep(arg1:string,arg2:string):Promise<void>;
