// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddStepToTask(arg1, arg2) {
  return window['go']['services']['TaskService']['AddStepToTask'](arg1, arg2);
}

export function CreateTask(arg1) {
  return window['go']['services']['TaskService']['CreateTask'](arg1);
}

export function DeleteAllTasks() {
  return window['go']['services']['TaskService']['DeleteAllTasks']();
}

export function DeleteStep(arg1, arg2) {
  return window['go']['services']['TaskService']['DeleteStep'](arg1, arg2);
}

export function DeleteTask(arg1) {
  return window['go']['services']['TaskService']['DeleteTask'](arg1);
}

export function EditStep(arg1, arg2, arg3) {
  return window['go']['services']['TaskService']['EditStep'](arg1, arg2, arg3);
}

export function EditTask(arg1, arg2) {
  return window['go']['services']['TaskService']['EditTask'](arg1, arg2);
}

export function GetStepsByTaskId(arg1, arg2) {
  return window['go']['services']['TaskService']['GetStepsByTaskId'](arg1, arg2);
}

export function GetTasks(arg1) {
  return window['go']['services']['TaskService']['GetTasks'](arg1);
}

export function SetContext(arg1) {
  return window['go']['services']['TaskService']['SetContext'](arg1);
}

export function ToggleStep(arg1, arg2) {
  return window['go']['services']['TaskService']['ToggleStep'](arg1, arg2);
}
