name: Cross Platform Release

on:
    push:
        tags:
            - '*'

env:
    NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                build:
                    - name: "App"
                      platform: "linux/amd64"
                      os: "ubuntu-latest"
                    - name: "App"
                      platform: "windows/amd64"
                      os: "windows-latest"
                    - name: "App"
                      platform: "darwin/amd64"
                      os: "macos-latest"
        
        runs-on: ${{ matrix.build.os }}

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: 'recursive'
            
            - name: Build Wails App
              uses: dAppServer/wails-build-action@main
              id: build
              with:
                build-name: ${{ matrix.build.name }}
                build-platform: ${{ matrix.build.platform }}
                package: false
                go-version: "1.24"